site_name: DCI 295D - Digital Editions
base_url: https://mackenziekbrooks.github.io/dci295d-f23-digitaleditions

theme: 
  name: material
  icon:
    admonition:
      abstract: material/head-cog
      question: fontawesome/solid/laptop-code
      example: fontawesome/solid/code
      warning: material/book

  features:
      - navigation.tabs
      - navigation.sections

  palette: 
    primary: red

  logo: images/noun-book.png
  favicon: images/noun-book-5924288.png

extra_css:
  - styles/website.css


plugins:
  - search

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: "#"

nav:
  - Course Info:
    - Course info: index.md
    - Policies: policies.md
    - Protocols: protocols.md
  - Schedule: schedule.md
  - Assignments:
    - Assignments: assignments.md
    - Specs Grading: grading.md
